#!/usr/bin/env python3
"""Generate Flyto2 Blueprint source and catalog references."""

from __future__ import annotations

import argparse
import ast
from pathlib import Path
import sys
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "flyto_blueprint"
OUTPUT = ROOT / "docs" / "reference"
HEADER = "<!-- Generated by scripts/generate-reference.py; do not edit. -->\n\n"


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def link(path: Path, line: int = 1) -> str:
    relative = rel(path)
    return f"[`{relative}:{line}`](https://github.com/flytohub/flyto-blueprint/blob/main/{relative}#L{line})"


def clean(value: Any, limit: int = 240) -> str:
    text = " ".join(str(value or "").split()).replace("|", "\\|")
    return text if len(text) <= limit else text[: limit - 3] + "..."


def module_summary(tree: ast.Module) -> str:
    doc = ast.get_docstring(tree, clean=True)
    return clean(doc.split("\n\n", 1)[0] if doc else "Internal package module.")


def declaration_rows(path: Path) -> list[tuple[int, str, str, str]]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    rows: list[tuple[int, str, str, str]] = []

    def visit(nodes: list[ast.stmt], owner: str = "", in_class: bool = False) -> None:
        for node in nodes:
            if isinstance(node, ast.ClassDef):
                qualified = f"{owner}.{node.name}" if owner else node.name
                bases = ", ".join(ast.unparse(base) for base in node.bases)
                signature = f"class {qualified}({bases})" if bases else f"class {qualified}"
                purpose = clean(ast.get_docstring(node, clean=True) or "See the linked implementation.")
                rows.append((node.lineno, "class", signature, purpose))
                visit(node.body, qualified, True)
            elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                qualified = f"{owner}.{node.name}" if owner else node.name
                prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
                returns = f" -> {ast.unparse(node.returns)}" if node.returns else ""
                signature = f"{prefix} {qualified}({ast.unparse(node.args)}){returns}"
                purpose = clean(ast.get_docstring(node, clean=True) or "See the linked implementation.")
                rows.append((node.lineno, "method" if in_class else "function", signature, purpose))
                visit(node.body, qualified, False)

    visit(tree.body)
    return sorted(rows)


def python_reference() -> str:
    files = sorted(PACKAGE.rglob("*.py"))
    total = 0
    parts = [HEADER, "# Python Implementation Reference\n\n"]
    inventories: list[tuple[Path, int, int, str]] = []
    grouped: list[tuple[Path, list[tuple[int, str, str, str]]]] = []
    for path in files:
        text = path.read_text(encoding="utf-8")
        tree = ast.parse(text, filename=str(path))
        rows = declaration_rows(path)
        total += len(rows)
        inventories.append((path, len(text.splitlines()), len(rows), module_summary(tree)))
        grouped.append((path, rows))

    parts.append(f"Generated inventory: **{len(files)} modules** and **{total} class/function/method declarations**.\n\n")
    parts.append("## Modules\n\n| Module | Lines | Declarations | Responsibility |\n|---|---:|---:|---|\n")
    for path, lines, count, purpose in inventories:
        parts.append(f"| {link(path)} | {lines} | {count} | {purpose} |\n")

    for path, rows in grouped:
        if not rows:
            continue
        parts.append(f"\n## `{rel(path)}`\n\n| Kind | Signature | Responsibility | Source |\n|---|---|---|---|\n")
        for line, kind, signature, purpose in rows:
            parts.append(f"| {kind} | `{clean(signature)}` | {purpose} | {link(path, line)} |\n")
    return "".join(parts)


def blueprint_reference() -> str:
    parts = [HEADER, "# Packaged Blueprint Catalog\n\n"]
    records = []
    for path in sorted((PACKAGE / "blueprints").rglob("*.yaml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        steps = data.get("steps", [])
        modules = sorted({str(step.get("module", "")) for step in steps if isinstance(step, dict) and step.get("module")})
        records.append((path, data, modules))
    patterns = sum(1 for path, _, _ in records if "blocks" not in path.parts)
    blocks = len(records) - patterns
    block_label = "composition block" if blocks == 1 else "composition blocks"
    parts.append(f"The package ships **{patterns} blueprints** and **{blocks} {block_label}**.\n\n")
    parts.append("| ID | Kind | Purpose | Tags | Arguments | Step modules | Source |\n|---|---|---|---|---|---|---|\n")
    for path, data, modules in records:
        kind = "block" if "blocks" in path.parts else "blueprint"
        args = data.get("args", {})
        arg_names = ""
        if isinstance(args, dict):
            arg_names = ", ".join(
                f"{name}{'*' if isinstance(definition, dict) and definition.get('required') else ''}"
                for name, definition in args.items()
            )
        parts.append(
            f"| `{clean(data.get('id', path.stem))}` | {kind} | {clean(data.get('description', data.get('name', '')))} | "
            f"`{clean(', '.join(map(str, data.get('tags', []))))}` | `{clean(arg_names)}` | `{clean(', '.join(modules))}` | {link(path)} |\n"
        )
    parts.append("\n`*` marks a required argument. Expansion and validation behavior is documented in [../API.md](../API.md).\n")
    return "".join(parts)


def mcp_reference() -> str:
    path = PACKAGE / "tools.py"
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    tools = []
    for node in tree.body:
        if not isinstance(node, ast.Assign) or not node.targets or not isinstance(node.targets[0], ast.Name):
            continue
        if not node.targets[0].id.endswith("_TOOL"):
            continue
        try:
            value = ast.literal_eval(node.value)
        except (TypeError, ValueError):
            continue
        if isinstance(value, dict):
            tools.append((node.lineno, value))
    parts = [HEADER, "# MCP Tool Schemas\n\n", f"`get_blueprint_tools()` publishes **{len(tools)} tool definitions**.\n\n"]
    for line, tool in tools:
        schema = tool.get("inputSchema", {})
        required = set(schema.get("required", []))
        parts.append(f"## `{tool.get('name', '')}`\n\n{clean(tool.get('description', ''), 500)}\n\nDefinition: {link(path, line)}.\n\n")
        properties = schema.get("properties", {})
        if properties:
            parts.append("| Input | Type | Required | Purpose |\n|---|---|---|---|\n")
            for name, definition in properties.items():
                parts.append(f"| `{name}` | `{definition.get('type', 'any')}` | {'yes' if name in required else 'no'} | {clean(definition.get('description', ''))} |\n")
            parts.append("\n")
    return "".join(parts)


def outputs() -> dict[Path, str]:
    index = HEADER + """# Generated Reference

- [Python implementation](python-api.md): every package module, class, function, nested function, and method.
- [Blueprint catalog](blueprint-catalog.md): every packaged blueprint and composition block.
- [MCP schemas](mcp-tools.md): every tool, input, and required field.

Run `python3 scripts/generate-reference.py` after changing these surfaces. CI checks the same output with `--check`.
"""
    documents = {
        OUTPUT / "README.md": index,
        OUTPUT / "python-api.md": python_reference(),
        OUTPUT / "blueprint-catalog.md": blueprint_reference(),
        OUTPUT / "mcp-tools.md": mcp_reference(),
    }
    return {path: content.rstrip() + "\n" for path, content in documents.items()}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(rel(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        print("stale generated documentation:\n" + "\n".join(stale), file=sys.stderr)
        return 1
    print("generated documentation: PASS" if args.check else "generated documentation: updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
